const Group = require('../models/Group') 
const User = require('../models/User') 
const Post = require('../models/Post') 
const Comment = require('../models/Comment') 

Group.hasMany(Post)
Group.hasMany(User)
User.hasMany(Post)
User.hasMany(Comment)
User.belongsTo(Group)
Post.belongsTo(User)
Post.belongsTo(Group)
Post.hasMany(Comment)
Comment.belongsTo(User)
Comment.belongsTo(Post)